# language - available by default : en, fr, de, se, cn, es, ja, sk, lt, hu, pl, id, ru, zh, ko
lang: en

# force the music played on join (players can't disable it)
forceJoinMusic: false

# open the plugin GUI when a player click on a jukebox block with a disc
jukeboxClick: false

# send plugin message when starting/stopping music...
sendMessages: true

# load files asynchronously
asyncLoading: false

# list of worlds where music will be enabled (empty = all)
enabledWorlds: []

# note particles
noteParticles: true

# enable or not action bar messages instead of chat (not available on 1.8)
actionBar: false

# enable or not server radio
radio: true

# automatically play the radio when a player joins
radioOnJoin: false

# reload the song the player was listening to before it left the server
reloadOnJoin: true

# material of songs in the GUI. Examples: DIRT, GOLD_INGOT. Any invalid material will lead to random records.
songItem: RANDOM_RECORD

# name of songs items (variables: NAME, ID, AUTHOR)
itemFormat: "{NAME}    | {ID}"

# formatted songs name (variables: NAME, ID, AUTHOR)
songFormat: "\"{NAME}\", {AUTHOR}"

# player options gived to new players
defaultPlayerOptions:
  volume: 70
  join: false
  shuffle: false
  particles: false
  repeat: false